[book]
authors = ["Pavel Eliseev"]
language = "ru"
multilingual = false
src = "src"
title = "Документация modern-g7-32"

[output.html]
additional-css = ["typst-doc.css"]

[preprocessor.typst-doc]
command = "../target/debug/mdbook-typst-doc"
default-type-class = "obj"

[preprocessor.typst-doc.types]
int = {link = "https://typst.app/docs/reference/foundations/int/", class = "num"}
float = {link = "https://typst.app/docs/reference/foundations/float/", class = "num"}
angle = {link = "https://typst.app/docs/reference/layout/angle/", class = "num"}
color = {class = "color", link = "https://typst.app/docs/reference/visualize/color/"}
gradient = {class = "color", link = "https://typst.app/docs/reference/visualize/gradient/"}
content = {link = "https://typst.app/docs/reference/foundations/content/", class = "con"}
bool = {link = "https://typst.app/docs/reference/foundations/bool/", class = "bool"}
str = {link  = "https://typst.app/docs/reference/foundations/str/", class = "str"}
auto = {class = "keyword"}
none = {class = "keyword"}
pattern = {link = "https://typst.app/docs/reference/visualize/pattern/"}
stroke = {link = "https://typst.app/docs/reference/visualize/stroke/"}
dictionary = {link = "https://typst.app/docs/reference/foundations/dictionary/"}
array = {link = "https://typst.app/docs/reference/foundations/array/"}
direction = {link = "https://typst.app/docs/reference/layout/direction/"}